name: 08 OIDC Demo

on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  list-buckets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::655700896650:role/awar08-gha-role
          aws-region: us-east-1

      - name: verify whoami
        run: aws sts get-caller-identity
      - name: List S3 buckets
        run: aws s3 ls